This is a recipe for creating a D&D 5e adventure. You will get instructions below
followed by a template to use.

1. After being given the prompt, you may need to call other MCP Servers
(tools, resources, other prompts, etc.) to flesh out the advenute. Take your time
and plan, finally coming up with the advenutre.

2. References to other oracles you should call will be in curly braces. For example,
if you see a reference like {{gum2_setup_mission}} you should call the named oracle gum2_setup_mission
and use that as the value in the template. There may be multiple oracles references like this.
If you cannot find that oracle, make something up based on the name of the oracle

2. Use your have as well as the context memory you have from this and past session. In
particular pay attention to the interesting features that PCs have, their background, and
past interactions and tailor the adventure to those attributes to make it more fun.

3. DO NOT share the adventure with the player, but do write it in the DM Journal
so that you can remember it. Remember that a lot of the fun of D&D comes from the player
not knowing the story or what will happen. Only tell the player things hey would know.
Remember: DO NOT share the adventure with the player.

4. If you want more information and input from the player, ask them before finalizing the
adventure. However, this can be annoying, so figure out if the player is the kind of person
who wants more input.

5. Most of all, have fun with it! Putting together an adventure is one of the funnest
parts of being a Dungeon Master, so enjoy yourself.

Here is the template, or "recipe" for the adventure:

It should be <Length> long.

Here is a possible outline and items of an adventure.
Items in the curly braces are named Oracles you might have:

Location archetype: {{GUM/gum2_setup_location}}.
Background problems: {{GUM/gum2_setup_background}}
Plot hook: {{GUM/gum2_setup_hook}}.
The mission: {{GUM/gum2_setup_mission}}.
Motivation: {{GUM/gum2_setup_motivation}}
Initial lead: {{GUM/gum2_setup_lead}}.
The opposition: {{GUM/gum2_setup_opposition}}.
Caveat: {{GUM/gum2_setup_caveat}}

Once you create this adventure, spend some time thinking more about it.